services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=latest
    volumes:
      - D:\:/media
      - ./backup/plex/config:/config
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
      - ./backup/radarr/config:/config
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
      - ./backup/sonarr/config:/config
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./backup/prowlarr/config:/config
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    restart: unless-stopped 

  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    network_mode: host
    volumes:
      - D:\:/media
    # devices:
    #   - /dev/sr0:/dev/sr0
    #   - /dev/sg2:/dev/sg2
    restart: unless-stopped

  # Default user is admin
  # Password is found in /config/supervisor.log
  # Change password and also update default download path as neeeded
  # Ensure media is downloaded to a location that can be accessed
  # Open VPN config expected in `backup/qbittorrent/config/openvpn`
  # Credentials in .env
  qbittorrent:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent
    network_mode: bridge
    environment:
      - VPN_ENABLED=yes
      - VPN_CLIENT=openvpn
      - VPN_PROV=custom
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - WEBUI_PORT=8080
      - ENABLE_STARTUP_SCRIPTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=yes
      - SOCKS_USER=admin
      - SOCKS_PASS=socks
      - UMASK=000
      - PUID=0
      - PGID=0
    ports:
      - 8080:8080
      - 8099:8099
      - 8099:8099/udp
      - 8118:8118
      - 9118:9118
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
      - ./backup/qbittorrent/config:/config
    restart: unless-stopped