services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=latest
    volumes:
      - D:\:/media
      - ./backup/plex/config:/config
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - D:\:/media
      - ./backup/radarr/config:/config
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - D:\:/media
      - ./backup/sonarr/config:/config
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./backup/prowlarr/config:/config
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Etc/UTC
    restart: unless-stopped 

  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    network_mode: host
    volumes:
      - D:\:/media
    # devices:
    #   - /dev/sr0:/dev/sr0
    #   - /dev/sg2:/dev/sg2
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
        - PUID=1000 
        - PGID=1000
        - TZ=Etc/UTC
        - WEBUI_PORT=8080
        - TORRENTING_PORT=6881
    volumes:
        - ./backup/qbittorrent/config:/config
        - D:\:/media

    restart: unless-stopped