services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=Etc/UTC
      - VERSION=latest
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
        bind:
            propagation: shared
      - ./backup/plex/config:/config
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    mem_limit: 12g
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
        bind:
            propagation: shared
      - ./backup/radarr/config:/config
    mem_limit: 8g
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
        bind:
            propagation: shared
      - ./backup/sonarr/config:/config
    mem_limit: 8g
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./backup/prowlarr/config:/config
    mem_limit: 4g
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: host
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./backup/overseerr/config:/config
    mem_limit: 8g
    restart: unless-stopped

  # makemkv:
  #   image: jlesage/makemkv:latest
  #   container_name: makemkv
  #   network_mode: host
  #   volumes:
  #     - D:\:/media
  #   # devices:
  #   #   - /dev/sr0:/dev/sr0
  #   #   - /dev/sg2:/dev/sg2
  #   mem_limit: 8g
  #   restart: unless-stopped

  # Default user is admin
  # Password is found in /config/supervisor.log
  # Change password and also update default download path as neeeded
  # Ensure media is downloaded to a location that can be accessed
  # Open VPN config expected in `backup/qbittorrent/config/openvpn`
  # Credentials in .env
  qbittorrent:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent
    network_mode: bridge
    environment:
      - VPN_ENABLED=yes
      - VPN_CLIENT=openvpn
      - VPN_PROV=custom
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - WEBUI_PORT=8080
      - ENABLE_STARTUP_SCRIPTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=yes
      - SOCKS_USER=admin
      - SOCKS_PASS=socks
      - UMASK=000
    ports:
      - 8080:8080
      - 8099:8099
      - 8099:8099/udp
      - 8118:8118
      - 9118:9118
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: D:/
        target: /media
        consistency: delegated
        bind:
            propagation: shared
      - ./backup/qbittorrent/config:/config
    mem_limit: 8g
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    network_mode: bridge
    ports:
      - 7077:3000
    mem_limit: 2g
    environment: 
      - HOMEPAGE_VAR_PLEX_API_KEY=${HOMEPAGE_VAR_PLEX_API_KEY}
    volumes:
      - ./services.yaml:/app/config/services.yaml # Link the services.yaml file
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ./docs/images/plex.png:/app/public/icons/plex.png
    restart: unless-stopped